packages:
  - "apps/*"
  - "tooling/*"

catalog:
  eslint: ^9.18.0
  prettier: ^3.3.3
  tailwindcss: ^3.4.17
  typescript: ^5.7.3
  zod: ^3.23.8

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.11
    "@types/react-dom": ^18.3.1
